### ISSUE TITLE
ROS2 Domain Change: Not every topic type can be used

### ISSUE THREAD

**Issue by lsiefkebeuth** [eProsima/Integration-Service#23]
Helllo, I tried to change the domain of a few topics and noticed that not every topic type can be used. In the not working case, `soss` prints no output, launches nodes in both domains and subscribes and creates the according topics but publishes nothing into them.

Not working: sensor_msgs/Imu, sensor_msgs/LaserScan, sensor_msgs/CameraInfo
Working: rosgraph_msgs/Clock, sensor_msgs/Image, sensor_msgs/PointCloud2

My `domain_change_turtlebot.yaml`:
```
systems:
     gazebo: { type: ros2, domain: 0, node_name: "gazeboToRobot"}
     robot1: { type: ros2, domain: 1, node_name: "gazebo" }
routes:
    gazeboToRobot1: { from: gazebo, to: robot1 } 
    robot1ToGazebo: {from: robot1, to: gazebo}
topics:
    camera/image_raw: {type: "sensor_msgs/Image", route: gazeboToRobot1}
    camera/camera_info: {type: "sensor_msgs/CameraInfo", route: gazeboToRobot1}
    clock: { type: "rosgraph_msgs/Clock", route: gazeboToRobot1 }
    cmd_vel: {type: "geometry_msgs/Twist", route: robot1ToGazebo}
    imu: {type: "sensor_msgs/Imu", route: gazeboToRobot1}
    odom: { type: "nav_msgs/Odometry", route: gazeboToRobot1}
    scan: {type: "sensor_msgs/LaserScan", route: gazeboToRobot1}
    tf: {type: "tf2_msgs/TFMessage", route: gazeboToRobot1}
    tf_static: {type: "tf2_msgs/TFMessage", route: gazeboToRobot1}
 ```

What I did:
 - Cloned the project in a ROS2 workspace
 - Edited CMakeLists.txt of ros2-test
   - added
```
find_package(builtin_interfaces REQUIRED)
find_package(rosgraph_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(tf2_msgs REQUIRED)
find_package(std_msgs REQUIRED)
```
   - changed
```
soss_rosidl_mix(
  PACKAGES geometry_msgs nav_msgs test_msgs
  MIDDLEWARES ros2
)
```
into
```
soss_rosidl_mix(
  PACKAGES builtin_interfaces std_msgs geometry_msgs nav_msgs test_msgs rosgraph_msgs sensor_msgs tf2_msgs 
  MIDDLEWARES ros2
)
```
 - run `ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py`
 - run `soss domain_change_turtlebot.yaml`

**Comment by Briancbn** [comment]
Hi, just compiling the ros2-test is not enough. Did you add the respective package names into the ros1-test as well, which they currently hosted on another [repository](https://github.com/osrf/soss-ros1/blob/master/packages/ros1-test/CMakeLists.txt#L16)?

**Comment by mxgrey** [comment]
@Briancbn I think the `soss-ros1` content isn't needed here because the goal is to move messages between two different ROS2 domains (e.g. two systems have different `ROS_DOMAIN_ID` values, and you want some of the topics to be visible between those systems).

I'm not sure off the top of my head why those specific message types would be failing. My best guess is that they are touching on some edge case in the way `soss::Message` is storing message data to pass between the systems.

The current `soss::Message` class was only meant to be a prototype, so I'm not shocked that it would be exhibiting some bugs. We're working with eProsima to replace it with a much more robust data structure in this PR: https://github.com/osrf/soss/pull/20 although that's a work-in-progress, and I'm not sure how long it will take to finish it.

If your use case is urgent, then I could potentially help you debug it if you're able to get any more information about how exactly it's failing. Maybe you can compile in debug mode by passing `-DCMAKE_BUILD_TYPE=Debug` to cmake and then run your failing soss instance through `gdb`?

**Comment by lsiefkebeuth** [comment]
Thanks for your help!
As I don't use ROS1, I do not think `soss-ros1` affects the ROS2 domain change.

My use case is to share data between ROS2 enabled robots which are seperated with different DDS domains. The problem is not urgent and if you plan to replace the code which probably contains the error, I don't think we should spend to much effort into it.

**Comment by jamoralp** [comment]
Good morning,

It has been a while since this issue was addressed, so I just wanted to make sure, before closing it, that I give you the most updated information possible:

* `SOSS` has been migrated to *Integration Service* and all the products were restructured, including the System Handles. Now, every System Handle lives in its own repository; for this particular case, the [ROS 2 System handle](https://github.com/eProsima/ROS2-SH) is what you are looking for.
* I have tried some of the cases you mention and they work correctly. Here you have a screenshot of *Integration Service* translating from domain 5 to 10, for a `sensor_msgs/Imu` topic:

  ![image](https://user-images.githubusercontent.com/45167093/119635425-f6d8ee00-be13-11eb-8ffa-9c92502d0fc6.png)
  
  To test this, I have slighly modified the [ROS 2 domain ID tutorial](https://integration-service.docs.eprosima.com/en/latest/examples/same_protocol/ros2_change_domain.html):
  *  In the compilation command `colcon build`, I used the new `ROS2_MIX_PACKAGES` variable, [available for the ROS2 System Handle](https://integration-service.docs.eprosima.com/en/latest/user_manual/systemhandle/ros2_sh.html#compilation-flags). This flag accepts a list of ROS 2 packages to automatically find them for you and execute the `rosidl_mix` step:
    ```bash
    colcon build --cmake-args -DMIX_ROS2_PACKAGES="sensor_msgs"
    ```
  * I added the following topic to the [configuration file](https://github.com/eProsima/Integration-Service/blob/main/examples/basic/ros2__domain_id_change.yaml):
    ```yaml
    topics:
         ....
         imu_topic: { type: "sensor_msgs/Imu", route: domain_5_to_10 }
    ```

Hope this is helpful.
Regards
